name: Integration Test

on:
  pull_request: {}
  push:
    branches:
    - main
  schedule:
  # we run integration tests every day to make sure it works with the latest version of kubelogin
  - cron: '0 0 * * *' # daily at 00:00 UTC

jobs:
  test-latest-versions:
    strategy:
      matrix:
        kubelogin-version:
        - latest
        - '*'
        - ''
        - 'v0.0.24'
        - 'v0.0.23'
        skip-cache:
        - true
        - false
    uses: ./.github/workflows/test-kubelogin.yaml
    with:
      kubelogin-version: ${{ matrix.kubelogin-version }}
      skip-cache: ${{ matrix.skip-cache }}
      with-github-token: 'true'
    secrets: inherit
    permissions:
      contents: read

  test-specified-versions-no-github-token:
    strategy:
      matrix:
        kubelogin-version:
        - 'v0.0.24'
        - 'v0.0.23'
        skip-cache:
        - true
        - false
    uses: ./.github/workflows/test-kubelogin.yaml
    with:
      kubelogin-version: ${{ matrix.kubelogin-version }}
      skip-cache: ${{ matrix.skip-cache }}
      with-github-token: 'false'
    secrets: inherit
    permissions:
      contents: read

  test-specified-versions-with-github-token:
    strategy:
      matrix:
        kubelogin-version:
        - 'v0.0.24'
        - 'v0.0.23'
        skip-cache:
        - true
        - false
    uses: ./.github/workflows/test-kubelogin.yaml
    with:
      kubelogin-version: ${{ matrix.kubelogin-version }}
      skip-cache: ${{ matrix.skip-cache }}
      with-github-token: 'true'
    secrets: inherit

  test-github-api-override:
    strategy:
      matrix:
        github-api-base-url:
        - ''
        - 'https://api.github.com'
    uses: ./.github/workflows/test-kubelogin.yaml
    with:
      kubelogin-version: 'latest'
      github-api-base-url: ${{ matrix.github-api-base-url }}
      with-github-token: 'true'
      skip-cache: true
    secrets: inherit

  test-github-api-override-bad-case:
    strategy:
      matrix:
        github-api-base-url:
        - 'https://example.com' # failing example
    uses: ./.github/workflows/test-kubelogin.yaml
    with:
      kubelogin-version: 'latest'
      github-api-base-url: ${{ matrix.github-api-base-url }}
      with-github-token: 'true'
      skip-cache: true
      # there are expected test failrues to show the github-api-base-url usage,
      # it's fine to ignore the error for such cases.
      continue-on-error: true
    secrets: inherit
    permissions:
      contents: read
