name: Test workflow

on:
  workflow_dispatch:
    inputs:
      kubelogin-version:
        description: 'kubelogin version to use'
        required: true
        default: '*'

jobs:
  test:
    strategy:
      matrix:
        # TODO(hbc): add ARM64 runners
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
      name: Checkout code
    - uses: ./ # use current branch
      name: Setup kubelogin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        kubelogin-version: ${{ github.event.inputs.kubelogin-version }}
    - run: |
        kubelogin --version
      name: Invoke kubelogin

  test-windows:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      name: Checkout code
    - uses: ./ # use current branch
      name: Setup kubelogin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        kubelogin-version: ${{ github.event.inputs.kubelogin-version }}
    # FIXME(hbc): github actions doesn't support step level if condition
    - run: |
        env
        kubelogin.exe --version
      name: Invoke kubelogin
