name: Unit Test

on:
  pull_request: {}
  push:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      with:
        node-version: 16
    - run: npm ci
    - run: npm run test-ci
